### ISSUE TITLE
`waitUsing` throwing unbind error

### ISSUE THREAD

**Issue by joshhanley** [glhd/dawn#3]
Loving the package so far! 😁

**Describe the bug**
I've been experimenting with getting Livewire internal component testing running using Dawn.

Livewire has some Dusk macros that we use in Livewire's Dusk tests.

One of them is `waitForLivewireToLoad()`, which uses the Dusk method `waitUsing()`. See here

https://github.com/livewire/livewire/blob/65d311c63d2d1092ad5891fd0c1c1bdbed272cee/src/Macros/DuskBrowserMacros.php#L120-L128

Currently with Dawn, it throws an exception

> There was 1 error:
> 
> 1) Tests\Feature\SampleTest::testExample
> ErrorException: Cannot unbind $this of closure using $this
> 
> /Users/josh/TestSites/LivewirePlayground/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:259
> /Users/josh/TestSites/LivewirePlayground/vendor/glhd/dawn/src/Browser/Commands/Wait/WaitUsing.php:29
> /Users/josh/TestSites/LivewirePlayground/vendor/glhd/dawn/src/Browser/Concerns/ExecutesWaitCommands.php:25
> /Users/josh/TestSites/LivewirePlayground/vendor/livewire/livewire/src/Macros/DuskBrowserMacros.php:126
> /Users/josh/TestSites/LivewirePlayground/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:124
> /Users/josh/TestSites/LivewirePlayground/vendor/livewire/livewire/src/LivewireManager.php:127
> /Users/josh/TestSites/LivewirePlayground/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:338
> /Users/josh/TestSites/LivewirePlayground/tests/Feature/SampleTest.php:31

**What version does this affect?**
I've just been experimenting in a test app running:
 - Laravel Version: 9.27.0
 - Package Version: dev-main as at 6 Oct (Commit https://github.com/glhd/dawn/commit/7cf1eece4c53698d04b7565b94a7e16f3a9dbd5a)

**To Reproduce**
Have pushed my experiment to this Repo and branch https://github.com/joshhanley/LivewirePlayground/tree/livewire-dusk-dawn-test

Steps below:

Create a Livewire component

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Main extends Component
{
    public function render()
    {
        return <<< 'HTML
        <div>App</div>
        HTML;
    }
}
```

Add this to `TestCase.php`

```php
use Glhd\Dawn\Browser;
use Illuminate\Support\Facades\Route;
use Livewire\Macros\DuskBrowserMacros;

public function setUp(): void
{
    parent::setUp();

    Browser::mixin(new DuskBrowserMacros);

    Route::get('/livewire-dusk/{component}', function ($component) {
        $class = urldecode($component);

    return app()->call(new $class());
    })->middleware('web');
}
```

Create a test

```php
public function testExample()
{
    $class = Main::class;
    $queryString = '';
    $url = '/livewire-dusk/'.urlencode($class).$queryString;

    $this->openBrowser()
        ->visit($url)
        ->waitForLivewireToLoad()
        ->assertSeeIn('body', 'App')
        ;
}
```

**Expected behavior**
Test should wait for Livewire to load and then continue with the assertion `assertSeeIn()`.

**Additional context**
Browser opens and the component loads and I can briefly see "App" displayed on the screen before the exception happens. So I know the loading of the Livewire component is working happily.

Currently if I remove the `->waitForLivewireToLoad()` call, the test passes. But naturally it is required to wait for Livewire to finish loading before progressing with the test, so we can test all the Livewire things 😁

Hope this helps!

**Comment by inxilpro** [comment]
Can you try changing `return $this->waitUsing(6, 25, function () {` to `return $this->waitUsing(6, 25, static function () {` in the `DuskBrowserMacros` (add the `static` keyword to the closure) and see if that works? This is a known issue with the multi-process nature of Dawn.

**Comment by inxilpro** [comment]
Looking at the macros a bit more, it could be that more of them need to be updated to work with Dawn. I'm also willing to add some of those macros directly into Dawn so that they don't need to be macro'd in (things like `assertHasClass` that make sense for everyone). We already have Vue-specific code, and I'm planning on adding similar Alpine-specific code, so I don't see a reason to not have Livewire-specific functions, too.

**Comment by joshhanley** [comment]
@inxilpro added the static keyword to the closure and got a different error:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/882837/194405199-e845e7cf-e8b7-4875-bdd1-fda02941b355.png">

And VSCode isn't happy about it either:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/882837/194405149-07986141-23b9-4717-9ee6-1d849069c377.png">

Yeah agreed re the macros probably needing updating. Was just testing to see how much would work out of the box. I think we can get them running first then look at adding them into Dawn.

**Comment by inxilpro** [comment]
Hah, yes. I guess I could have looked at the very next line!

How about:

```php
public function waitForLivewireToLoad()
{
  return function () {
    /** @var \Laravel\Dusk\Browser $this */
    return $this->waitUsing(6, 25, static function ($driver) {
      return $driver->executeScript("return !! window.Livewire.components.initialRenderIsFinished");
    });
  };
}
```

The `waitUsing()` callback receives the web driver instance as its first argument (or if you type-hint `BrowserManager` then it can receive that, instead).

**Comment by joshhanley** [comment]
@inxilpro yep, once I woke up and my brain started working, that's how I got it running (type hinting the `BrowserManager`)! 😁

There is a bug though in the `WaitUsing` command, the `$this->firstClosureParameterType()` call throws an exception if there is no parameter or if there is no parameter type.

Updated it to this to get it running

```php
protected function getClosure(BrowserManager $manager): Closure
{
    $closure = $this->closure->getClosure();

    // If our wait callback needs access to the BrowserManager instance, we'll need
    // to wrap it in a native "until" callback because that's handled inside the webdriver package.
    
    try {
        $firstParameterType = $this->firstClosureParameterType($closure);
    } catch(RuntimeException $e) {
        $firstParameterType = null;
    }

    if (BrowserManager::class === $firstParameterType) {
        return static function() use ($closure, $manager) {
            return $closure($manager);
        };
    }

    return $closure;
}
```

Let me know if you want me to PR that fix

**Comment by inxilpro** [comment]
Oh, good catch. I just fixed in my working branch.

I'm also going to implement most of the `DuskBrowserMacros` directly in Dawn. We already have support for Vue, and I'm planning to add support for Alpine, so I see no reason not to have a few Livewire-specific helpers, too.

**Comment by inxilpro** [comment]
Take a look at the latest `dev-main` release (as of 30 seconds ago). It should be a better starting point—eventually the macros probably can go away (there are still a handful that need to be implemented).

**Comment by joshhanley** [comment]
@inxilpro no worries!

Sweet sounds good 😁

You'll be pleased to know that this works (with tweaks to `waitForLivewireToLoad()` and `waitForLivewire()`)

```php
Livewire::visit($this->openBrowser(), Main::class)
    ->assertSeeIn('body', 'App')
    ->waitForLivewire(function($browser) {
        $browser->click('#toggle');
    })
    ->assertSeeIn('body', 'New')
    ;
```

For some reason though, using the higher order `->waitForLivewire()->click('#toggle')` instead of the closure won't work yet. Still trying to work that one out. It currently just times out and won't run the `waitUntil` closure provided by the anonymous class.

Here are the methods with changes

```php
public function waitForLivewireToLoad()
{
    return function () {
        /** @var \Laravel\Dusk\Browser $this */
        return $this->waitUsing(6, 25, static function ($driver) {
            return $driver->executeScript("return !! window.Livewire.components.initialRenderIsFinished");
        });
    };
}

public function waitForLivewire()
{
    return function ($callback = null) {
        /** @var \Laravel\Dusk\Browser $this */
        $id = str()->random();

        $this->script([
            "window.duskIsWaitingForLivewireRequest{$id} = true",
            "window.Livewire.hook('message.sent', () => { window.duskIsWaitingForLivewireRequest{$id} = true })",
            "window.Livewire.hook('message.processed', () => { delete window.duskIsWaitingForLivewireRequest{$id} })",
            "window.Livewire.hook('message.failed', () => { delete window.duskIsWaitingForLivewireRequest{$id} })",
        ]);

        if ($callback) {
            $callback($this);

            return $this->waitUsing(6, 25, static function ($driver) use ($id) {
                return $driver->executeScript("return window.duskIsWaitingForLivewireRequest{$id} === undefined");
            }, 'Livewire request was never triggered');
        }

        // If no callback is passed, make ->waitForLivewire a higher-order method.
        return new class($this, $id) {
            public function __construct($browser, $id) { $this->browser = $browser; $this->id = $id; }

            public function __call($method, $params)
            {
                $id = $this->id;

                return tap($this->browser->{$method}(...$params), function ($browser) use ($id) {
                    $browser->waitUsing(6, 25, static function ($driver) use ($id) {
                        return $driver->executeScript("return window.duskIsWaitingForLivewireRequest{$id} === undefined");
                    }, 'Livewire request was never triggered');
                });
            }
        };
    };
}
```

**Comment by joshhanley** [comment]
> Take a look at the latest `dev-main` release (as of 30 seconds ago). It should be a better starting point—eventually the macros probably can go away (there are still a handful that need to be implemented).

Github didn't show me this reply for some reason 😕 yep will have a play!

**Comment by joshhanley** [comment]
Closing this as Chris has built in support for Livewire out of the box 😁
